apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-admin-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitea-admin-secret
  dataFrom:
  - extract:
      key: gitea-admin-secret
      metadataPolicy: None
      conversionStrategy: Default
      decodingStrategy: None
