apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (printf "%s-sa" .Release.Name) }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    serviceaccount/purpose: "community-job-access"
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-job-reader
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    {{- if .Values.community.migration.upgradeEnabled }}
    migration/scope: "job-reader"
    {{- end }}
    rbac/role: "job-reader"
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-job-reader-binding
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    rbac/binding: "job-reader-to-sa"
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default (printf "%s-sa" .Release.Name) }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-job-reader
  apiGroup: rbac.authorization.k8s.io