# templates/service.yaml
apiVersion: {{ .Values.service.apiVersion }}
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Values.service.app }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ ternary "ClusterIP" "LoadBalancer" .Values.service.ingress.enabled }}
  
  {{- if not .Values.service.ingress.enabled }}
  loadBalancerIP: {{ .Values.global.externalIP }}
  externalTrafficPolicy: Cluster
  {{- end }}
  
  ports:
  {{- if .Values.community.config.community.enableSubpathBasedAccess }}
  - port: {{ .Values.service.ports.subpath.port }}
    targetPort: {{ .Values.service.ports.subpath.targetPort }}
    protocol: TCP
    name: {{ .Values.service.ports.subpath.name }}
  {{- else }}
  - port: {{ .Values.service.ports.frontend.port }}
    targetPort: {{ .Values.service.ports.frontend.targetPort }}
    protocol: {{ .Values.service.ports.frontend.protocol }}
    name: {{ .Values.service.ports.frontend.name }}
  
  - port: {{ .Values.service.ports.admin.port }}
    targetPort: {{ .Values.service.ports.admin.targetPort }}
    protocol: {{ .Values.service.ports.admin.protocol }}
    name: {{ .Values.service.ports.admin.name }}
  
  - port: {{ .Values.service.ports.backend.port }}
    targetPort: {{ .Values.service.ports.backend.targetPort }}
    protocol: {{ .Values.service.ports.backend.protocol }}
    name: {{ .Values.service.ports.backend.name }}
  {{- end }}
  
  selector:
    app: {{ .Values.service.selector.app }}