replicacount: 0
postgresql:
  persistence:
    enabled: true
    storageClass: nfs-csi

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: wiki.vmtlw.ru
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: wikijs
              port:
                number: 80
  tls:
  - hosts:
      - wiki.vmtlw.ru
    secretName: vmtlw-ru-tls
    


