image:
  repository: privatebin/nginx-fpm-alpine
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: ""

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: paste.vmtlw.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - paste.vmtlw.ru
      secretName: pastebin-tls
