apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-env
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-env
  dataFrom:
  - extract:
      key: grafana-env
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
