apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-forgejo-postgresql-0
  namespace: forgejo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
  volumeMode: Filesystem
