apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-applications
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:vmtlw/not-so-awesome-gitops-infra-fork.git
      revision: home
      directories:
      - path: applications-helm/**/*
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:vmtlw/not-so-awesome-gitops-infra-fork.git
        targetRevision: 'home'
        path: '{{path}}'
        plugin: {}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
        - /webhooks/4/clientConfig/caBundle
        - /webhooks/5/clientConfig/caBundle
        - /webhooks/6/clientConfig/caBundle
        - /webhooks/7/clientConfig/caBundle
        - /webhooks/8/clientConfig/caBundle
        - /webhooks/9/clientConfig/caBundle
        - /webhooks/10/clientConfig/caBundle
        - /webhooks/11/clientConfig/caBundle
        - /webhooks/12/clientConfig/caBundle
        - /webhooks/13/clientConfig/caBundle
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/template/spec/containers/0/env/0/valueFrom/resourceFieldRef/divisor
        - /spec/template/spec/containers/0/env/1/valueFrom/resourceFieldRef/divisor
        - /spec/template/spec/initContainers/0/env/0/valueFrom/resourceFieldRef/divisor
        - /spec/template/spec/initContainers/0/env/1/valueFrom/resourceFieldRef/divisor
