apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: non-helm-applications
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:vmtlw/not-so-awesome-gitops-infra-fork.git
      revision: home
      directories:
      - path: applications-raw/**/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:vmtlw/not-so-awesome-gitops-infra-fork.git
        targetRevision: 'home'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
