apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: sftpgo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 10Gi
