repositories:
- name: csi-driver-nfs
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts

releases:
- name: csi-driver-nfs
  chart: csi-driver-nfs/csi-driver-nfs
  version: 4.11.0
  values:
  - ./values.yaml
