storageClass:
  create: true
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  parameters:
    server: 10.0.0.5
    share: /srv/nfs
    #subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}/${pv.metadata.name}
    subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
    mountPermissions: "0"
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  mountOptions:
    - nfsvers=4.1
