# Global PostgreSQL settings
global:
  postgresql:
    auth:
      username: bn_keycloak
      password: bn_keycloak
      database: bitnami_keycloak

# Keycloak Admin User Configuration
auth:
  adminUser: admin
  adminPassword: admin

# PostgreSQL Specific Configuration
postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: bn_keycloak
    database: bitnami_keycloak

# Additional Keycloak Environment Variables
extraEnvVars:
  - name: KC_PRODUCTION
    value: "true"
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: VERTX_WORKER_POOL_SIZE
    value: "20"
  - name: VERTX_EVENT_LOOP_POOL_SIZE
    value: "8"

ingress:
  enabled: true
  pathType: ImplementationSpecific
  hostname: id.vmtlw.ru
  ingressClassName: "nginx"
  path: "{{ .Values.httpRelativePath }}"
  servicePort: http
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: true
  selfSigned: false
