command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--hostname-strict=false"
extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: admin
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

ingress:
  enabled: true
  ingressClassName: "nginx"
  servicePort: http
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  rules:
    -
      host: id.vmtlw.ru
      paths:
        - path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/'
          pathType: Prefix
  tls:
    - hosts:
        - id.vmtlw.ru
      secretName: "anon-tls"


console:
  enabled: true
  ingressClassName: "nginx"
  servicePort: http
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    rules:
      -
        host: id.vmtlw.ru
        paths:
          - path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/admin'
            pathType: Prefix
  tls:
    - hosts:
        - id.vmtlw.ru
      secretName: "anon-tls"
