apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: "8.2.5"
    helm:
      releaseName: argocd
      values: |
        global:
          addPrometheusAnnotations: true
          domain: gitops.vmtlw.ru
          securityContext:
            fsGroup: 999

        redis-ha:
          enabled: false

        controller:
          replicas: 1

        server:
          replicas: 1
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              nginx.ingress.kubernetes.io/backend-protocol: HTTP
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            tls: true
            extraTls:
              - hosts:
                - gitops.vmtlw.ru
                secretName: vmtlw-tls


        repoServer:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: argocd-repo-server
                topologyKey: kubernetes.io/hostname
          extraArgs:
            - --parallelismlimit=3
          repoCacheExpiration: 180
          replicas: 1
          volumes:
            - name: homeargocdcache
              emptyDir: {}
            - name: homeargocdconfig
              emptyDir: {}
            - name: custom-tools
              emptyDir: {}
            - emptyDir:
                medium: Memory
              name: helmfile-tmp
          initContainers:
            - name: install-kustomize
              image: alpine:3.13
              command: ["/bin/sh", "-c"]
              args:
                - |
                  wget -O - https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.4.0/kustomize_v4.4.0_linux_amd64.tar.gz | tar xz && mv kustomize /custom-tools/
              volumeMounts:
                - mountPath: /custom-tools
                  name: custom-tools
          extraContainers:
            - name: plugin
              image: lucj/argocd-plugin-helmfile:latest
              command: ["/var/run/argocd/argocd-cmp-server"]
              securityContext:
                readOnlyRootFilesystem: false
                runAsNonRoot: true
                runAsUser: 999
              env:
                - name: PATH
                  value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/custom-tools
              volumeMounts:
                - mountPath: /tmp
                  name: helmfile-tmp
                - mountPath: /var/run/argocd
                  name: var-files
                - mountPath: /home/argocd/.cache
                  name: homeargocdcache
                - mountPath: /home/argocd/.config
                  name: homeargocdconfig
                - mountPath: /home/argocd/cmp-server/plugins
                  name: plugins
                - mountPath: /custom-tools
                  name: custom-tools

        applicationSet:
          replicaCount: 1

        configs:
          cm:
            create: true
            exec.enabled: true
          params: 
            reposerver.parallelism.limit: 3
            server.insecure: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

