apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.2.0
    helm:
      values: |
        repoServer:
          extraContainers:
            - name: cmp-helmfile
              image: ghcr.io/helmfile/helmfile:v0.157.0
              imagePullPolicy: IfNotPresent
              command: [/var/run/argocd/argocd-cmp-server]
              securityContext:
                runAsNonRoot: true
                runAsUser: 999
              volumeMounts:
                - mountPath: /var/run/argocd
                  name: var-files
                - mountPath: /home/argocd/cmp-server/plugins
                  name: plugins
                - mountPath: /home/argocd/cmp-server/config/plugin.yaml
                  subPath: plugin.yaml
                  name: cmp-helmfile
                - mountPath: /tmp
                  name: cmp-tmp
        
          volumes:
            - name: var-files
              emptyDir: {}
        
            - name: plugins
              emptyDir: {}
        
            - name: cmp-helmfile
              configMap:
                name: cmp-helmfile
        
            - name: cmp-tmp
              emptyDir: {}




  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
