apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.2.0
    helm:
      values: |
        repoServer:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: argocd-repo-server
                topologyKey: kubernetes.io/hostname
          extraArgs:
            - --parallelismlimit=3
          repoCacheExpiration: 180
          replicas: 1
          volumes:
            - name: homeargocdcache
              emptyDir: {}
            #  persistentVolumeClaim:
            #    claimName: pvc-argocd-homeargocd
            - name: homeargocdconfig
              emptyDir: {}
            #  persistentVolumeClaim:
            #    claimName: pvc-argocd-homeargocd-config
            - name: custom-tools
              emptyDir: {}
            - emptyDir:
                medium: Memory
              name: helmfile-tmp
          initContainers:
            - name: install-kustomize
              image: alpine:3.22
              command: ["/bin/sh", "-c"]
              args:
                - |
                  wget -O - https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.7.1/kustomize_v5.7.1_linux_amd64.tar.gz | tar xz && mv kustomize /custom-tools/
              volumeMounts:
                - mountPath: /custom-tools
                  name: custom-tools
          extraContainers:
          - name: plugin
            image: lucj/argocd-plugin-helmfile:latest
            command: ["/var/run/argocd/argocd-cmp-server"]
            securityContext:
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 999
            env:
              - name: PATH
                value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/custom-tools
            volumeMounts:
            - mountPath: /tmp
              name: helmfile-tmp
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/.cache
              name: homeargocdcache
            - mountPath: /home/argocd/.config
              name: homeargocdconfig
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /custom-tools
              name: custom-tools

        applicationSet:
          replicaCount: 1

        configs:
          params:
            reposerver.parallelism.limit: 3
          cm:
            accounts.admin: apiKey
            timeout.reconciliation: 360s
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

