apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:vmtlw/not-so-awesome-gitops-infra-fork.git
    targetRevision: home
    path: applicationsets
    directory:
      recurse: false
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
