apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "privatebin.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "privatebin.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "privatebin.name" . }}
    spec:
      containers:
        - name: privatebin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /srv/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "privatebin.fullname" . }}-pvc
