apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      restartPolicy: Always
      containers:
        - name: mailserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 1200m
              memory: 5000Mi
            requests:
              cpu: 700m
              memory: 2000Mi
          ports:
            - containerPort: 25
            - containerPort: 110
            - containerPort: 143
            - containerPort: 587
            - containerPort: 993
            - containerPort: 995
            - containerPort: 4190
            - containerPort: 80
          securityContext:
            privileged: true
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: webmail
              mountPath: /opt/www/webmail
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: posteio-data
        - name: webmail
          persistentVolumeClaim:
            claimName: posteio-webmail

