apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: default
      caProvider:
        key: ca.crt
        name: vault-tls
        namespace: vault
        type: Secret
      path: secret
      server: https://vault.vault.svc.cluster.local:8200
      version: v2
