kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: vault
  name: vault-role
rules:
- apiGroups: [""]
  resources: ["pods", "secrets"]
  verbs: ["get", "update", "patch", "create"]
