valkey-cluster:
  enabled: false
valkey:
  enabled: true
postgresql:
  enabled: true
  persistence:
    enabled: true
    storageClass: nfs-csi
postgresql-ha:
  enabled: false
persistence:
  enabled: true
  storageClass: nfs-csi
gitea:
  admin:
    existingSecret: gitea-admin-secret
  config:
    database:
      DB_TYPE: postgres
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: git.vmtlw.ru
  tls:
    - secretName: git-vmtlw-ru-tls
      hosts:
        - git.vmtlw.ru
