apiVersion: v1
kind: Service
metadata:
  name: vuetorrent
  namespace: vuetorrent
  labels:
    app: vuetorrent
spec:
  type: ClusterIP
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .port }}
    {{- end }}
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8090

  selector:
    app: vuetorrent

