image:
  repository: lscr.io/linuxserver/jackett
  tag: latest
  pullPolicy: IfNotPresent

timezone: Europe/Moscow
replicaCount: 1

persistence:
  config:
    enabled: true
    size: 1Gi
  downloads:
    enabled: true
    size: 5Gi

service:
  type: ClusterIP
  port: 9117

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: jackett.vmtlw.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: jackett-tls
      hosts:
        - jackett.vmtlw.ru
