controller:
  hostNetwork: true
  hostPort:
    enabled: true
  allowSnippetAnnotations: true
  kind: DaemonSet
  dnsPolicy: ClusterFirstWithHostNet
  service:
    enabled: false
  metrics:
    enabled: false

